services:
  db:
    restart: always
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

volumes:
  database:
